# Generated by Django 5.0.6 on 2026-05-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolyhavenAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('tags', models.JSONField(default=list)),
                ('dim_x', models.FloatField(default=0)),
                ('dim_y', models.FloatField(default=0)),
                ('dim_z', models.FloatField(default=0)),
                ('thumb_url', models.URLField(blank=True, default='')),
                ('glb_url', models.URLField(blank=True, default='')),
                ('local_path', models.CharField(blank=True, default='', max_length=512)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
